Homework1
made-ml-in-prod-2021/zingykizz pull request #2
Opened 2021-05-08 15:05 UTC by ZingyKizz

Проект имеет модульную структуру, реализованы необходимые методы чтения, обработки данных, обучения модели, сбора метрик. Тесты не написаны.

2021-05-09 13:11 UTC, ol-ga-00 commented
> Проект имеет модульную структуру, реализованы необходимые методы чтения, обработки данных, обучения модели, сбора метрик. Тесты не написаны.

Если этим предложением вы хотите выполнить последний пункт домашнего задания (провести самооценку), то его необходимо скорректировать. Нужно по пунктам расписать, за что вы заслуживаете баллы по вашему мнению

2021-05-12 19:10 UTC, ol-ga-00 commented
-2) Назовите ветку homework1 (1 балл) -- 1
-1) положите код в папку ml_project -- 0
0) В описании к пулл реквесту описаны основные "архитектурные" и тактические решения, которые сделаны в вашей работе. В общем, описание что именно вы сделали и для чего, чтобы вашим ревьюерам было легче понять ваш код. (2 балла) -- 1
 
1) Выполнение EDA, закоммитьте ноутбук в папку с ноутбуками (2 баллов) -- 0
Вы так же можете построить в ноутбуке прототип(если это вписывается в ваш стиль работы)
Можете использовать не ноутбук, а скрипт, который сгенерит отчет, закоммитьте и скрипт и отчет (за это + 1 балл) -- 1 
 
2) Проект имеет модульную структуру(не все в одном файле =) ) (2 баллов) -- 0 
 > Чтобы получить 2 балла, необходимо создать какую-нибудь папку в ml_project (например, src/), и поместить в неё только! питоновские скрипты (setup.py в неё помещать не нужно; train_pipeline.py -- по желанию)
 
3) использованы логгеры (2 балла) -- 2
> Но было бы здорово производить логирование и в models/, features/
 
4) написаны тесты на отдельные модули и на прогон всего пайплайна(3 баллов) -- 0
 
5) Для тестов генерируются синтетические данные, приближенные к реальным (3 баллов) -- 0
- можно посмотреть на библиотеки https://faker.readthedocs.io/en/, https://feature-forge.readthedocs.io/en/latest/
- можно просто руками посоздавать данных, собственноручно написанными функциями
как альтернатива, можно закоммитить файл с подмножеством трейна(это не оценивается)  
 
6) Обучение модели конфигурируется с помощью конфигов в json или yaml, закоммитьте как минимум 2 корректные конфигурации, с помощью которых можно обучить модель (разные модели, стратегии split, preprocessing) (3 балла) -- 1
> Наблюдаю только один конфиг. Существующий конфиг используется не полноценно, например, в конфиге есть параметр model_type, но в коде он никак не учитывается, всегда используется LogisticRegression
 
7) Используются датаклассы для сущностей из конфига, а не голые dict (3 балла) -- 3
 
8) Используйте кастомный трансформер(написанный своими руками) и протестируйте его(3 балла) -- 0
 
9) Обучите модель, запишите в readme как это предлагается (3 балла) -- 3
 
10) напишите функцию predict, которая примет на вход артефакт/ы от обучения, тестовую выборку(без меток) и запишет предикт, напишите в readme как это сделать (3 балла)  -- 1
> В README об этом ничего не написано. Не понятно каким скриптом можно произвести предсказание 
 
11) Используется hydra  (https://hydra.cc/docs/intro/) (3 балла - доп баллы) -- 0
 
12) Настроен CI(прогон тестов, линтера) на основе github actions  (3 балла - доп баллы (будем проходить дальше в курсе, но если есть желание поразбираться - welcome) -- 0
13) Проведите самооценку, опишите, в какое колво баллов по вашему мнению стоит оценить вашу работу и почему (1 балл доп баллы)  -- 0
 

Прошу посмотреть и сказать, согласны ли вы с баллами. Также у вас ещё есть возможность внести правки и увеличить свои баллы

2021-05-12 19:12 UTC, ol-ga-00 requested changes
Очень плохо коммитить бинарники. 
Если есть возможность этого не делать, то лучше не делать. 
Я про model.pkl

2021-05-16 19:31 UTC, mrgsv reviewed
Согласен с оценкой, которая была поставлена `ol-ga-00 `

2021-05-16 19:31 UTC, mrgsv commented on ml_project/.gitignore
> +
я думаю, что можно добавить сюда .pkl, чтобы не коммитить бинарники

2021-05-16 19:31 UTC, mrgsv commented on ml_project/README.md
> +~~~
нужно подробнее расписать README

2021-05-16 19:31 UTC, mrgsv commented on ml_project/reports/make_report.py
> +from pandas_profiling import ProfileReport
Иногда pandas_profiling работает не слишком быстро, поэтому можно использовать sweetviz.

2021-05-22 17:50 UTC, ZingyKizz commented
Выполнение EDA, закоммитьте ноутбук в папку с ноутбуками (2 баллов) -- 0
Закоммитил ноутбук с EDA

Проект имеет модульную структуру(не все в одном файле =) ) (2 баллов) -- 0 
Сделал

Обучение модели конфигурируется с помощью конфигов в json или yaml, закоммитьте как минимум 2 корректные конфигурации, с помощью которых можно обучить модель (разные модели, стратегии split, preprocessing) (3 балла) -- 1 - Добавил еще один конфиг для обучения с другой моделью, параметрами сплита

напишите функцию predict, которая примет на вход артефакт/ы от обучения, тестовую выборку(без меток) и запишет предикт, напишите в readme как это сделать (3 балла) -- 1
Реализовал пайплайн для получения предсказаний

2021-05-22 19:40 UTC, ol-ga-00 approved these changes
Ставлю 21 балл

2021-05-23 19:05 UTC, merged